-- Dados iniciais (fictícios): usuários padrão, categorias e 40 chamados com histórico, comentários e triagens.
-- As datas são relativas ao momento da migration para manter o dashboard sempre com dados recentes.
CREATE FUNCTION pg_temp.ha(minutos integer) RETURNS timestamp AS $$ SELECT (now() AT TIME ZONE 'utc') - make_interval(mins => minutos) $$ LANGUAGE sql;

INSERT INTO "usuarios" ("id", "nome", "email", "senha_hash", "perfil") VALUES
  (1, 'Ana Atendente', 'admin@helpdesk.local', crypt('admin123', gen_salt('bf', 10)), 'ATENDENTE'),
  (2, 'Sérgio Solicitante', 'solicitante@helpdesk.local', crypt('solicitante123', gen_salt('bf', 10)), 'SOLICITANTE');

INSERT INTO "categorias" ("id", "nome") VALUES
  (1, 'Acesso/Login'),
  (2, 'Financeiro'),
  (3, 'Bug no sistema'),
  (4, 'Dúvida'),
  (5, 'Infraestrutura');

INSERT INTO "chamados" ("id", "titulo", "descricao", "solicitante_nome", "solicitante_email", "categoria_id", "prioridade", "status", "criado_em", "atualizado_em", "resolvido_em") VALUES
  (1, 'Não consigo acessar o sistema após troca de senha', 'Troquei a senha ontem à tarde e desde então aparece a mensagem de usuário ou senha inválidos. Já tentei limpar o cache do navegador.', 'Carla Menezes', 'carla.menezes@exemplo.com', 1, 'ALTA', 'EM_ANDAMENTO', pg_temp.ha(36445), pg_temp.ha(36249), NULL),
  (2, 'Conta bloqueada por excesso de tentativas', 'Minha conta foi bloqueada depois de errar a senha três vezes. Preciso do desbloqueio para emitir os relatórios de hoje.', 'Rafael Tavares', 'rafael.tavares@exemplo.com', 1, 'MEDIA', 'ABERTO', pg_temp.ha(3782), pg_temp.ha(3782), NULL),
  (3, 'Solicito acesso ao módulo de relatórios', 'Fui transferido para o time de planejamento e preciso de permissão de leitura no módulo de relatórios gerenciais.', 'Juliana Prado', 'juliana.prado@exemplo.com', 1, 'BAIXA', 'EM_ANDAMENTO', pg_temp.ha(22062), pg_temp.ha(21998), NULL),
  (4, 'Autenticação em dois fatores não envia o código', 'O código de verificação não chega por SMS. Meu telefone cadastrado é (48) 99812-3456, confirmei que está correto.', 'Marcos Vieira', 'marcos.vieira@exemplo.com', 1, 'ALTA', 'CANCELADO', pg_temp.ha(29517), pg_temp.ha(29079), NULL),
  (5, 'Link de redefinição de senha expirado', 'Cliquei no link de redefinição recebido por e-mail e a página informa que o link expirou, mesmo tendo aberto em poucos minutos.', 'Beatriz Lacerda', 'beatriz.lacerda@exemplo.com', 1, 'MEDIA', 'FECHADO', pg_temp.ha(25289), pg_temp.ha(21803), pg_temp.ha(24305)),
  (6, 'Ninguém do time comercial consegue logar', 'Desde as 8h nenhum usuário do comercial consegue entrar no sistema. A tela fica carregando e volta para o login.', 'Thiago Antunes', 'thiago.antunes@exemplo.com', 1, 'CRITICA', 'RESOLVIDO', pg_temp.ha(5824), pg_temp.ha(5470), pg_temp.ha(5470)),
  (7, 'Alterar e-mail de login', 'Mudei de área e meu e-mail corporativo mudou. Gostaria de atualizar o e-mail usado no login.', 'Fernanda Rocha', 'fernanda.rocha@exemplo.com', 1, 'BAIXA', 'FECHADO', pg_temp.ha(69932), pg_temp.ha(67308), pg_temp.ha(69447)),
  (8, 'Sessão expira a cada poucos minutos', 'O sistema me desloga a cada cinco minutos mais ou menos, mesmo enquanto estou preenchendo formulários.', 'Lucas Moraes', 'lucas.moraes@exemplo.com', 1, 'MEDIA', 'EM_ANDAMENTO', pg_temp.ha(36788), pg_temp.ha(36579), NULL),
  (9, 'Boleto gerado com valor incorreto', 'O boleto da fatura de setembro saiu com valor diferente do contrato. O correto seria R$ 1.250,00 e saiu R$ 1.520,00.', 'Patrícia Duarte', 'patricia.duarte@exemplo.com', NULL, 'ALTA', 'ABERTO', pg_temp.ha(3976), pg_temp.ha(3976), NULL),
  (10, 'Nota fiscal não chegou por e-mail', 'A nota fiscal referente ao pagamento do mês passado não foi enviada para o e-mail financeiro da empresa.', 'André Sampaio', 'andre.sampaio@exemplo.com', 2, 'MEDIA', 'FECHADO', pg_temp.ha(21148), pg_temp.ha(16411), pg_temp.ha(18722)),
  (11, 'Dúvida sobre data de vencimento', 'Gostaria de alterar a data de vencimento das próximas faturas do dia 5 para o dia 15.', 'Camila Freitas', 'camila.freitas@exemplo.com', 2, 'BAIXA', 'RESOLVIDO', pg_temp.ha(30685), pg_temp.ha(28929), pg_temp.ha(28929)),
  (12, 'Cobrança em duplicidade no cartão', 'Fui cobrado duas vezes pela mesma assinatura neste mês. Preciso do estorno de uma das cobranças.', 'Bruno Carvalho', 'bruno.carvalho@exemplo.com', 2, 'ALTA', 'FECHADO', pg_temp.ha(34481), pg_temp.ha(33010), pg_temp.ha(33099)),
  (13, 'Relatório de pagamentos com totais divergentes', 'O total exibido no relatório de pagamentos não bate com a soma das linhas exportadas para planilha.', 'Larissa Pires', 'larissa.pires@exemplo.com', 2, 'MEDIA', 'RESOLVIDO', pg_temp.ha(40820), pg_temp.ha(38352), pg_temp.ha(38352)),
  (14, 'Atualizar dados de faturamento', 'Precisamos atualizar a razão social e o endereço que aparecem nas notas fiscais emitidas.', 'Diego Fontes', 'diego.fontes@exemplo.com', 2, 'BAIXA', 'RESOLVIDO', pg_temp.ha(57674), pg_temp.ha(56808), pg_temp.ha(56808)),
  (15, 'Pagamento confirmado mas fatura segue em aberto', 'Paguei o boleto na segunda-feira e a fatura continua aparecendo como em aberto no portal.', 'Aline Barbosa', 'aline.barbosa@exemplo.com', 2, 'MEDIA', 'EM_ANDAMENTO', pg_temp.ha(5412), pg_temp.ha(5299), NULL),
  (16, 'Integração bancária parou de importar extratos', 'A conciliação automática não importa extratos desde ontem. O fechamento do mês depende disso.', 'Gustavo Neves', 'gustavo.neves@exemplo.com', 2, 'CRITICA', 'FECHADO', pg_temp.ha(28370), pg_temp.ha(24913), pg_temp.ha(25996)),
  (17, 'Erro 500 ao salvar cadastro de cliente', 'Ao clicar em salvar no cadastro de clientes aparece erro 500. Acontece com qualquer cliente novo.', 'Renata Coelho', 'renata.coelho@exemplo.com', 3, 'ALTA', 'CANCELADO', pg_temp.ha(2407), pg_temp.ha(2282), NULL),
  (18, 'Filtro por data não traz resultados', 'Na tela de pedidos, ao filtrar por período, a lista fica vazia mesmo havendo pedidos nas datas informadas.', 'Felipe Arruda', 'felipe.arruda@exemplo.com', 3, 'MEDIA', 'FECHADO', pg_temp.ha(56885), pg_temp.ha(53205), pg_temp.ha(54817)),
  (19, 'Texto cortado no botão de exportar', 'No celular o texto do botão exportar fica cortado e não dá para ler a opção.', 'Mariana Teles', 'mariana.teles@exemplo.com', 3, 'BAIXA', 'EM_ANDAMENTO', pg_temp.ha(37862), pg_temp.ha(37683), NULL),
  (20, 'Pedidos duplicados ao confirmar compra', 'Clientes relatam que ao confirmar a compra o pedido é criado duas vezes e o estoque baixa em dobro.', 'Rodrigo Brandão', 'rodrigo.brandao@exemplo.com', 3, 'CRITICA', 'RESOLVIDO', pg_temp.ha(80889), pg_temp.ha(76050), pg_temp.ha(76050)),
  (21, 'Upload de anexo falha com arquivos PDF', 'Ao anexar arquivos PDF acima de 2 MB o upload fica em 99% e depois mostra erro genérico.', 'Carla Menezes', 'carla.menezes@exemplo.com', 3, 'MEDIA', 'RESOLVIDO', pg_temp.ha(57243), pg_temp.ha(51857), pg_temp.ha(51857)),
  (22, 'Relatório de vendas trava o navegador', 'Ao gerar o relatório de vendas do trimestre o navegador congela e precisa ser fechado.', 'Rafael Tavares', 'rafael.tavares@exemplo.com', 3, 'ALTA', 'FECHADO', pg_temp.ha(38499), pg_temp.ha(30947), pg_temp.ha(32293)),
  (23, 'Ordenação da tabela de produtos invertida', 'Ao ordenar produtos por nome a lista vem de Z para A mesmo selecionando a ordem crescente.', 'Juliana Prado', 'juliana.prado@exemplo.com', 3, 'BAIXA', 'CANCELADO', pg_temp.ha(2050), pg_temp.ha(1551), NULL),
  (24, 'Notificações duplicadas no painel', 'Cada aviso aparece duas vezes no sino de notificações do painel principal.', 'Marcos Vieira', 'marcos.vieira@exemplo.com', 3, 'MEDIA', 'FECHADO', pg_temp.ha(21681), pg_temp.ha(19338), pg_temp.ha(20398)),
  (25, 'Como exportar a lista de clientes', 'Gostaria de saber se é possível exportar a lista de clientes em CSV e onde fica essa opção.', 'Beatriz Lacerda', 'beatriz.lacerda@exemplo.com', 4, 'BAIXA', 'RESOLVIDO', pg_temp.ha(5345), pg_temp.ha(4150), pg_temp.ha(4150)),
  (26, 'Diferença entre perfis de usuário', 'Qual a diferença entre o perfil gestor e o perfil analista? Preciso definir o perfil de um novo colaborador.', 'Thiago Antunes', 'thiago.antunes@exemplo.com', 4, 'BAIXA', 'RESOLVIDO', pg_temp.ha(24694), pg_temp.ha(24057), pg_temp.ha(24057)),
  (27, 'Como configurar aprovação em duas etapas', 'Queremos que pedidos acima de determinado valor passem por duas aprovações. Isso é configurável?', 'Fernanda Rocha', 'fernanda.rocha@exemplo.com', 4, 'MEDIA', 'CANCELADO', pg_temp.ha(4769), pg_temp.ha(4645), NULL),
  (28, 'Onde vejo o histórico de alterações', 'Existe algum lugar onde consigo ver quem alterou o cadastro de um fornecedor?', 'Lucas Moraes', 'lucas.moraes@exemplo.com', 4, 'BAIXA', 'FECHADO', pg_temp.ha(62232), pg_temp.ha(58940), pg_temp.ha(61297)),
  (29, 'Limite de usuários do plano', 'Quantos usuários simultâneos o nosso plano atual permite?', 'Patrícia Duarte', 'patricia.duarte@exemplo.com', NULL, 'BAIXA', 'ABERTO', pg_temp.ha(7071), pg_temp.ha(7071), NULL),
  (30, 'Integração com planilhas', 'É possível integrar os relatórios do sistema com planilhas online para atualização automática?', 'André Sampaio', 'andre.sampaio@exemplo.com', 4, 'MEDIA', 'ABERTO', pg_temp.ha(3471), pg_temp.ha(3471), NULL),
  (31, 'Treinamento para novos colaboradores', 'Vocês oferecem material de treinamento para novos usuários do sistema? Temos três pessoas começando.', 'Camila Freitas', 'camila.freitas@exemplo.com', 4, 'BAIXA', 'CANCELADO', pg_temp.ha(16954), pg_temp.ha(16758), NULL),
  (32, 'Personalizar campos do cadastro', 'Consigo adicionar um campo personalizado no cadastro de produtos para o código interno?', 'Bruno Carvalho', 'bruno.carvalho@exemplo.com', 4, 'BAIXA', 'FECHADO', pg_temp.ha(58284), pg_temp.ha(55777), pg_temp.ha(56853)),
  (33, 'Servidor de arquivos fora do ar', 'O servidor de arquivos compartilhados não responde desde as 7h. Nenhum setor consegue abrir documentos.', 'Larissa Pires', 'larissa.pires@exemplo.com', 5, 'CRITICA', 'ABERTO', pg_temp.ha(3674), pg_temp.ha(3674), NULL),
  (34, 'VPN desconectando com frequência', 'A VPN cai a cada 10 minutos para quem trabalha remoto, interrompendo chamadas e acesso aos sistemas.', 'Diego Fontes', 'diego.fontes@exemplo.com', NULL, 'ALTA', 'ABERTO', pg_temp.ha(417), pg_temp.ha(417), NULL),
  (35, 'Impressora do segundo andar não imprime', 'A impressora do segundo andar recebe os trabalhos mas não imprime. O painel não mostra erro.', 'Aline Barbosa', 'aline.barbosa@exemplo.com', 5, 'MEDIA', 'EM_ANDAMENTO', pg_temp.ha(34824), pg_temp.ha(34712), NULL),
  (36, 'Lentidão geral na rede da filial', 'A filial está com lentidão para acessar qualquer sistema desde a manhã. Testes de velocidade mostram queda grande.', 'Gustavo Neves', 'gustavo.neves@exemplo.com', 5, 'ALTA', 'EM_ANDAMENTO', pg_temp.ha(24094), pg_temp.ha(23898), NULL),
  (37, 'Solicitação de monitor adicional', 'Gostaria de solicitar um segundo monitor para a estação de trabalho do time de análise.', 'Renata Coelho', 'renata.coelho@exemplo.com', 5, 'BAIXA', 'EM_ANDAMENTO', pg_temp.ha(1550), pg_temp.ha(1407), NULL),
  (38, 'Certificado SSL do portal perto de expirar', 'O navegador mostra aviso de que o certificado do portal interno expira em cinco dias.', 'Felipe Arruda', 'felipe.arruda@exemplo.com', 5, 'MEDIA', 'RESOLVIDO', pg_temp.ha(43683), pg_temp.ha(42237), pg_temp.ha(42237)),
  (39, 'Backup noturno falhou', 'O relatório do backup indica falha na rotina noturna das duas últimas noites.', 'Mariana Teles', 'mariana.teles@exemplo.com', 5, 'ALTA', 'ABERTO', pg_temp.ha(11127), pg_temp.ha(11127), NULL),
  (40, 'Wi-Fi da sala de reuniões instável', 'A rede sem fio da sala de reuniões principal cai durante videochamadas.', 'Rodrigo Brandão', 'rodrigo.brandao@exemplo.com', 5, 'MEDIA', 'ABERTO', pg_temp.ha(4730), pg_temp.ha(4730), NULL);

INSERT INTO "historico_status" ("chamado_id", "status_anterior", "status_novo", "alterado_em", "alterado_por") VALUES
  (1, NULL, 'ABERTO', pg_temp.ha(36445), 'Carla Menezes'),
  (1, 'ABERTO', 'EM_ANDAMENTO', pg_temp.ha(36249), 'Ana Atendente'),
  (2, NULL, 'ABERTO', pg_temp.ha(3782), 'Rafael Tavares'),
  (3, NULL, 'ABERTO', pg_temp.ha(22062), 'Juliana Prado'),
  (3, 'ABERTO', 'EM_ANDAMENTO', pg_temp.ha(21998), 'Ana Atendente'),
  (4, NULL, 'ABERTO', pg_temp.ha(29517), 'Marcos Vieira'),
  (4, 'ABERTO', 'CANCELADO', pg_temp.ha(29079), 'Ana Atendente'),
  (5, NULL, 'ABERTO', pg_temp.ha(25289), 'Beatriz Lacerda'),
  (5, 'ABERTO', 'EM_ANDAMENTO', pg_temp.ha(25077), 'Ana Atendente'),
  (5, 'EM_ANDAMENTO', 'RESOLVIDO', pg_temp.ha(24305), 'Ana Atendente'),
  (5, 'RESOLVIDO', 'FECHADO', pg_temp.ha(21803), 'Ana Atendente'),
  (6, NULL, 'ABERTO', pg_temp.ha(5824), 'Thiago Antunes'),
  (6, 'ABERTO', 'EM_ANDAMENTO', pg_temp.ha(5640), 'Ana Atendente'),
  (6, 'EM_ANDAMENTO', 'RESOLVIDO', pg_temp.ha(5470), 'Ana Atendente'),
  (7, NULL, 'ABERTO', pg_temp.ha(69932), 'Fernanda Rocha'),
  (7, 'ABERTO', 'EM_ANDAMENTO', pg_temp.ha(69727), 'Ana Atendente'),
  (7, 'EM_ANDAMENTO', 'RESOLVIDO', pg_temp.ha(69447), 'Ana Atendente'),
  (7, 'RESOLVIDO', 'FECHADO', pg_temp.ha(67308), 'Ana Atendente'),
  (8, NULL, 'ABERTO', pg_temp.ha(36788), 'Lucas Moraes'),
  (8, 'ABERTO', 'EM_ANDAMENTO', pg_temp.ha(36579), 'Ana Atendente'),
  (9, NULL, 'ABERTO', pg_temp.ha(3976), 'Patrícia Duarte'),
  (10, NULL, 'ABERTO', pg_temp.ha(21148), 'André Sampaio'),
  (10, 'ABERTO', 'EM_ANDAMENTO', pg_temp.ha(20970), 'Ana Atendente'),
  (10, 'EM_ANDAMENTO', 'RESOLVIDO', pg_temp.ha(18722), 'Ana Atendente'),
  (10, 'RESOLVIDO', 'FECHADO', pg_temp.ha(16411), 'Ana Atendente'),
  (11, NULL, 'ABERTO', pg_temp.ha(30685), 'Camila Freitas'),
  (11, 'ABERTO', 'EM_ANDAMENTO', pg_temp.ha(30493), 'Ana Atendente'),
  (11, 'EM_ANDAMENTO', 'RESOLVIDO', pg_temp.ha(28929), 'Ana Atendente'),
  (12, NULL, 'ABERTO', pg_temp.ha(34481), 'Bruno Carvalho'),
  (12, 'ABERTO', 'EM_ANDAMENTO', pg_temp.ha(34321), 'Ana Atendente'),
  (12, 'EM_ANDAMENTO', 'RESOLVIDO', pg_temp.ha(33099), 'Ana Atendente'),
  (12, 'RESOLVIDO', 'FECHADO', pg_temp.ha(33010), 'Ana Atendente'),
  (13, NULL, 'ABERTO', pg_temp.ha(40820), 'Larissa Pires'),
  (13, 'ABERTO', 'EM_ANDAMENTO', pg_temp.ha(40639), 'Ana Atendente'),
  (13, 'EM_ANDAMENTO', 'RESOLVIDO', pg_temp.ha(38352), 'Ana Atendente'),
  (14, NULL, 'ABERTO', pg_temp.ha(57674), 'Diego Fontes'),
  (14, 'ABERTO', 'EM_ANDAMENTO', pg_temp.ha(57616), 'Ana Atendente'),
  (14, 'EM_ANDAMENTO', 'RESOLVIDO', pg_temp.ha(56808), 'Ana Atendente'),
  (15, NULL, 'ABERTO', pg_temp.ha(5412), 'Aline Barbosa'),
  (15, 'ABERTO', 'EM_ANDAMENTO', pg_temp.ha(5299), 'Ana Atendente'),
  (16, NULL, 'ABERTO', pg_temp.ha(28370), 'Gustavo Neves'),
  (16, 'ABERTO', 'EM_ANDAMENTO', pg_temp.ha(28289), 'Ana Atendente'),
  (16, 'EM_ANDAMENTO', 'RESOLVIDO', pg_temp.ha(25996), 'Ana Atendente'),
  (16, 'RESOLVIDO', 'FECHADO', pg_temp.ha(24913), 'Ana Atendente'),
  (17, NULL, 'ABERTO', pg_temp.ha(2407), 'Renata Coelho'),
  (17, 'ABERTO', 'CANCELADO', pg_temp.ha(2282), 'Ana Atendente'),
  (18, NULL, 'ABERTO', pg_temp.ha(56885), 'Felipe Arruda'),
  (18, 'ABERTO', 'EM_ANDAMENTO', pg_temp.ha(56860), 'Ana Atendente'),
  (18, 'EM_ANDAMENTO', 'RESOLVIDO', pg_temp.ha(54817), 'Ana Atendente'),
  (18, 'RESOLVIDO', 'FECHADO', pg_temp.ha(53205), 'Ana Atendente'),
  (19, NULL, 'ABERTO', pg_temp.ha(37862), 'Mariana Teles'),
  (19, 'ABERTO', 'EM_ANDAMENTO', pg_temp.ha(37683), 'Ana Atendente'),
  (20, NULL, 'ABERTO', pg_temp.ha(80889), 'Rodrigo Brandão'),
  (20, 'ABERTO', 'EM_ANDAMENTO', pg_temp.ha(80757), 'Ana Atendente'),
  (20, 'EM_ANDAMENTO', 'RESOLVIDO', pg_temp.ha(76050), 'Ana Atendente'),
  (21, NULL, 'ABERTO', pg_temp.ha(57243), 'Carla Menezes'),
  (21, 'ABERTO', 'EM_ANDAMENTO', pg_temp.ha(57203), 'Ana Atendente'),
  (21, 'EM_ANDAMENTO', 'RESOLVIDO', pg_temp.ha(51857), 'Ana Atendente'),
  (22, NULL, 'ABERTO', pg_temp.ha(38499), 'Rafael Tavares'),
  (22, 'ABERTO', 'EM_ANDAMENTO', pg_temp.ha(38437), 'Ana Atendente'),
  (22, 'EM_ANDAMENTO', 'RESOLVIDO', pg_temp.ha(32293), 'Ana Atendente'),
  (22, 'RESOLVIDO', 'FECHADO', pg_temp.ha(30947), 'Ana Atendente'),
  (23, NULL, 'ABERTO', pg_temp.ha(2050), 'Juliana Prado'),
  (23, 'ABERTO', 'CANCELADO', pg_temp.ha(1551), 'Ana Atendente'),
  (24, NULL, 'ABERTO', pg_temp.ha(21681), 'Marcos Vieira'),
  (24, 'ABERTO', 'EM_ANDAMENTO', pg_temp.ha(21582), 'Ana Atendente'),
  (24, 'EM_ANDAMENTO', 'RESOLVIDO', pg_temp.ha(20398), 'Ana Atendente'),
  (24, 'RESOLVIDO', 'FECHADO', pg_temp.ha(19338), 'Ana Atendente'),
  (25, NULL, 'ABERTO', pg_temp.ha(5345), 'Beatriz Lacerda'),
  (25, 'ABERTO', 'EM_ANDAMENTO', pg_temp.ha(5165), 'Ana Atendente'),
  (25, 'EM_ANDAMENTO', 'RESOLVIDO', pg_temp.ha(4150), 'Ana Atendente'),
  (26, NULL, 'ABERTO', pg_temp.ha(24694), 'Thiago Antunes'),
  (26, 'ABERTO', 'EM_ANDAMENTO', pg_temp.ha(24615), 'Ana Atendente'),
  (26, 'EM_ANDAMENTO', 'RESOLVIDO', pg_temp.ha(24057), 'Ana Atendente'),
  (27, NULL, 'ABERTO', pg_temp.ha(4769), 'Fernanda Rocha'),
  (27, 'ABERTO', 'CANCELADO', pg_temp.ha(4645), 'Ana Atendente'),
  (28, NULL, 'ABERTO', pg_temp.ha(62232), 'Lucas Moraes'),
  (28, 'ABERTO', 'EM_ANDAMENTO', pg_temp.ha(62081), 'Ana Atendente'),
  (28, 'EM_ANDAMENTO', 'RESOLVIDO', pg_temp.ha(61297), 'Ana Atendente'),
  (28, 'RESOLVIDO', 'FECHADO', pg_temp.ha(58940), 'Ana Atendente'),
  (29, NULL, 'ABERTO', pg_temp.ha(7071), 'Patrícia Duarte'),
  (30, NULL, 'ABERTO', pg_temp.ha(3471), 'André Sampaio'),
  (31, NULL, 'ABERTO', pg_temp.ha(16954), 'Camila Freitas'),
  (31, 'ABERTO', 'CANCELADO', pg_temp.ha(16758), 'Ana Atendente'),
  (32, NULL, 'ABERTO', pg_temp.ha(58284), 'Bruno Carvalho'),
  (32, 'ABERTO', 'EM_ANDAMENTO', pg_temp.ha(58069), 'Ana Atendente'),
  (32, 'EM_ANDAMENTO', 'RESOLVIDO', pg_temp.ha(56853), 'Ana Atendente'),
  (32, 'RESOLVIDO', 'FECHADO', pg_temp.ha(55777), 'Ana Atendente'),
  (33, NULL, 'ABERTO', pg_temp.ha(3674), 'Larissa Pires'),
  (34, NULL, 'ABERTO', pg_temp.ha(417), 'Diego Fontes'),
  (35, NULL, 'ABERTO', pg_temp.ha(34824), 'Aline Barbosa'),
  (35, 'ABERTO', 'EM_ANDAMENTO', pg_temp.ha(34712), 'Ana Atendente'),
  (36, NULL, 'ABERTO', pg_temp.ha(24094), 'Gustavo Neves'),
  (36, 'ABERTO', 'EM_ANDAMENTO', pg_temp.ha(23898), 'Ana Atendente'),
  (37, NULL, 'ABERTO', pg_temp.ha(1550), 'Renata Coelho'),
  (37, 'ABERTO', 'EM_ANDAMENTO', pg_temp.ha(1407), 'Ana Atendente'),
  (38, NULL, 'ABERTO', pg_temp.ha(43683), 'Felipe Arruda'),
  (38, 'ABERTO', 'EM_ANDAMENTO', pg_temp.ha(43544), 'Ana Atendente'),
  (38, 'EM_ANDAMENTO', 'RESOLVIDO', pg_temp.ha(42237), 'Ana Atendente'),
  (39, NULL, 'ABERTO', pg_temp.ha(11127), 'Mariana Teles'),
  (40, NULL, 'ABERTO', pg_temp.ha(4730), 'Rodrigo Brandão');

INSERT INTO "comentarios" ("chamado_id", "autor", "texto", "criado_em") VALUES
  (1, 'Ana Atendente', 'Estamos analisando o caso e retornamos assim que tivermos novidades.', pg_temp.ha(36343)),
  (1, 'Carla Menezes', 'Obrigado pelo retorno, fico no aguardo.', pg_temp.ha(36256)),
  (3, 'Ana Atendente', 'Estamos analisando o caso e retornamos assim que tivermos novidades.', pg_temp.ha(22014)),
  (5, 'Ana Atendente', 'Estamos analisando o caso e retornamos assim que tivermos novidades.', pg_temp.ha(25204)),
  (6, 'Ana Atendente', 'Estamos analisando o caso e retornamos assim que tivermos novidades.', pg_temp.ha(5789)),
  (6, 'Thiago Antunes', 'Obrigado pelo retorno, fico no aguardo.', pg_temp.ha(5490)),
  (7, 'Ana Atendente', 'Estamos analisando o caso e retornamos assim que tivermos novidades.', pg_temp.ha(69870)),
  (8, 'Ana Atendente', 'Estamos analisando o caso e retornamos assim que tivermos novidades.', pg_temp.ha(36670)),
  (8, 'Lucas Moraes', 'Obrigado pelo retorno, fico no aguardo.', pg_temp.ha(36581)),
  (10, 'Ana Atendente', 'Estamos analisando o caso e retornamos assim que tivermos novidades.', pg_temp.ha(21037)),
  (11, 'Ana Atendente', 'Estamos analisando o caso e retornamos assim que tivermos novidades.', pg_temp.ha(30662)),
  (11, 'Camila Freitas', 'Obrigado pelo retorno, fico no aguardo.', pg_temp.ha(30065)),
  (12, 'Ana Atendente', 'Estamos analisando o caso e retornamos assim que tivermos novidades.', pg_temp.ha(34424)),
  (12, 'Bruno Carvalho', 'Obrigado pelo retorno, fico no aguardo.', pg_temp.ha(34151)),
  (13, 'Ana Atendente', 'Estamos analisando o caso e retornamos assim que tivermos novidades.', pg_temp.ha(40774)),
  (14, 'Ana Atendente', 'Estamos analisando o caso e retornamos assim que tivermos novidades.', pg_temp.ha(57566)),
  (14, 'Diego Fontes', 'Obrigado pelo retorno, fico no aguardo.', pg_temp.ha(57436)),
  (15, 'Ana Atendente', 'Estamos analisando o caso e retornamos assim que tivermos novidades.', pg_temp.ha(5329)),
  (15, 'Aline Barbosa', 'Obrigado pelo retorno, fico no aguardo.', pg_temp.ha(4867)),
  (16, 'Ana Atendente', 'Estamos analisando o caso e retornamos assim que tivermos novidades.', pg_temp.ha(28272)),
  (18, 'Ana Atendente', 'Estamos analisando o caso e retornamos assim que tivermos novidades.', pg_temp.ha(56781)),
  (19, 'Ana Atendente', 'Estamos analisando o caso e retornamos assim que tivermos novidades.', pg_temp.ha(37752)),
  (19, 'Mariana Teles', 'Obrigado pelo retorno, fico no aguardo.', pg_temp.ha(37671)),
  (20, 'Ana Atendente', 'Estamos analisando o caso e retornamos assim que tivermos novidades.', pg_temp.ha(80798)),
  (20, 'Rodrigo Brandão', 'Obrigado pelo retorno, fico no aguardo.', pg_temp.ha(80528)),
  (21, 'Ana Atendente', 'Estamos analisando o caso e retornamos assim que tivermos novidades.', pg_temp.ha(57154)),
  (21, 'Carla Menezes', 'Obrigado pelo retorno, fico no aguardo.', pg_temp.ha(56801)),
  (22, 'Ana Atendente', 'Estamos analisando o caso e retornamos assim que tivermos novidades.', pg_temp.ha(38388)),
  (24, 'Ana Atendente', 'Estamos analisando o caso e retornamos assim que tivermos novidades.', pg_temp.ha(21563)),
  (25, 'Ana Atendente', 'Estamos analisando o caso e retornamos assim que tivermos novidades.', pg_temp.ha(5317)),
  (26, 'Ana Atendente', 'Estamos analisando o caso e retornamos assim que tivermos novidades.', pg_temp.ha(24647)),
  (28, 'Ana Atendente', 'Estamos analisando o caso e retornamos assim que tivermos novidades.', pg_temp.ha(62170)),
  (28, 'Lucas Moraes', 'Obrigado pelo retorno, fico no aguardo.', pg_temp.ha(61989)),
  (32, 'Ana Atendente', 'Estamos analisando o caso e retornamos assim que tivermos novidades.', pg_temp.ha(58265)),
  (35, 'Ana Atendente', 'Estamos analisando o caso e retornamos assim que tivermos novidades.', pg_temp.ha(34776)),
  (35, 'Aline Barbosa', 'Obrigado pelo retorno, fico no aguardo.', pg_temp.ha(34302)),
  (36, 'Ana Atendente', 'Estamos analisando o caso e retornamos assim que tivermos novidades.', pg_temp.ha(24055)),
  (36, 'Gustavo Neves', 'Obrigado pelo retorno, fico no aguardo.', pg_temp.ha(23579)),
  (37, 'Ana Atendente', 'Estamos analisando o caso e retornamos assim que tivermos novidades.', pg_temp.ha(1520)),
  (38, 'Ana Atendente', 'Estamos analisando o caso e retornamos assim que tivermos novidades.', pg_temp.ha(43583));

INSERT INTO "triagens_ia" ("chamado_id", "categoria_sugerida_id", "prioridade_sugerida", "resumo", "resposta_sugerida", "confianca", "modelo", "prompt_versao", "status", "erro", "tentativas", "latencia_ms", "tokens_entrada", "tokens_saida", "decidido_por", "decidido_em", "criado_em", "atualizado_em") VALUES
  (1, 1, 'ALTA', 'Não consigo acessar o sistema após troca de senha. Troquei a senha ontem à tarde e desde então aparece a mensagem de usuário ou senha inválidos. Já tentei limpar o cache do navegador.', 'Olá! Recebemos seu chamado sobre acesso. Vamos verificar sua conta e retornamos em breve com a liberação ou as próximas instruções.', 0.62, 'seed', 'triagem-v1', 'ACEITA', NULL, 1, 1477, 458, 252, 'Ana Atendente', pg_temp.ha(36425), pg_temp.ha(36444), pg_temp.ha(36444)),
  (2, 1, 'MEDIA', 'Conta bloqueada por excesso de tentativas. Minha conta foi bloqueada depois de errar a senha três vezes. Preciso do desbloqueio para emitir os relatórios de hoje.', 'Olá! Recebemos seu chamado sobre acesso. Vamos verificar sua conta e retornamos em breve com a liberação ou as próximas instruções.', 0.71, 'seed', 'triagem-v1', 'CONCLUIDA', NULL, 1, 835, 428, 255, NULL, NULL, pg_temp.ha(3781), pg_temp.ha(3781)),
  (3, 5, 'MEDIA', 'Solicito acesso ao módulo de relatórios. Fui transferido para o time de planejamento e preciso de permissão de leitura no módulo de relatórios gerenciais.', 'Olá! Recebemos o relato sobre a infraestrutura. A equipe de operações já está analisando e manteremos você atualizado.', 0.61, 'seed', 'triagem-v1', 'REJEITADA', NULL, 1, 985, 446, 253, 'Ana Atendente', pg_temp.ha(22022), pg_temp.ha(22061), pg_temp.ha(22061)),
  (4, 3, 'MEDIA', 'Autenticação em dois fatores não envia o código. O código de verificação não chega por SMS. Meu telefone cadastrado é (48) 99812-3456, confirmei que está correto.', 'Olá! Obrigado por relatar o problema. Já encaminhamos para o time técnico reproduzir o erro e retornaremos com uma previsão de correção.', 0.75, 'seed', 'triagem-v1', 'REJEITADA', NULL, 1, 886, 344, 138, 'Ana Atendente', pg_temp.ha(29502), pg_temp.ha(29516), pg_temp.ha(29516)),
  (5, 1, 'MEDIA', 'Link de redefinição de senha expirado. Cliquei no link de redefinição recebido por e-mail e a página informa que o link expirou, mesmo tendo aberto em poucos minutos.', 'Olá! Recebemos seu chamado sobre acesso. Vamos verificar sua conta e retornamos em breve com a liberação ou as próximas instruções.', 0.7, 'seed', 'triagem-v1', 'ACEITA', NULL, 1, 1920, 559, 245, 'Ana Atendente', pg_temp.ha(25267), pg_temp.ha(25288), pg_temp.ha(25288)),
  (6, 1, 'CRITICA', 'Ninguém do time comercial consegue logar. Desde as 8h nenhum usuário do comercial consegue entrar no sistema. A tela fica carregando e volta para o login.', 'Olá! Recebemos seu chamado sobre acesso. Vamos verificar sua conta e retornamos em breve com a liberação ou as próximas instruções.', 0.86, 'seed', 'triagem-v1', 'ACEITA', NULL, 1, 1396, 377, 185, 'Ana Atendente', pg_temp.ha(5791), pg_temp.ha(5823), pg_temp.ha(5823)),
  (7, 1, 'BAIXA', 'Alterar e-mail de login. Mudei de área e meu e-mail corporativo mudou. Gostaria de atualizar o e-mail usado no login.', 'Olá! Recebemos seu chamado sobre acesso. Vamos verificar sua conta e retornamos em breve com a liberação ou as próximas instruções.', 0.9, 'seed', 'triagem-v1', 'ACEITA', NULL, 1, 1311, 579, 160, 'Ana Atendente', pg_temp.ha(69917), pg_temp.ha(69931), pg_temp.ha(69931)),
  (8, 1, 'MEDIA', 'Sessão expira a cada poucos minutos. O sistema me desloga a cada cinco minutos mais ou menos, mesmo enquanto estou preenchendo formulários.', 'Olá! Recebemos seu chamado sobre acesso. Vamos verificar sua conta e retornamos em breve com a liberação ou as próximas instruções.', 0.79, 'seed', 'triagem-v1', 'ACEITA', NULL, 1, 1700, 329, 138, 'Ana Atendente', pg_temp.ha(36759), pg_temp.ha(36787), pg_temp.ha(36787)),
  (9, 2, 'ALTA', 'Boleto gerado com valor incorreto. O boleto da fatura de setembro saiu com valor diferente do contrato. O correto seria R$ 1.250,00 e saiu R$ 1.520,00.', 'Olá! Recebemos sua solicitação financeira. Nossa equipe vai conferir os lançamentos e retornar com a correção ou o esclarecimento.', 0.74, 'seed', 'triagem-v1', 'CONCLUIDA', NULL, 1, 841, 592, 142, NULL, NULL, pg_temp.ha(3975), pg_temp.ha(3975)),
  (10, 2, 'MEDIA', 'Nota fiscal não chegou por e-mail. A nota fiscal referente ao pagamento do mês passado não foi enviada para o e-mail financeiro da empresa.', 'Olá! Recebemos sua solicitação financeira. Nossa equipe vai conferir os lançamentos e retornar com a correção ou o esclarecimento.', 0.66, 'seed', 'triagem-v1', 'ACEITA', NULL, 1, 2486, 536, 164, 'Ana Atendente', pg_temp.ha(21108), pg_temp.ha(21147), pg_temp.ha(21147)),
  (11, 5, 'MEDIA', 'Dúvida sobre data de vencimento. Gostaria de alterar a data de vencimento das próximas faturas do dia 5 para o dia 15.', 'Olá! Recebemos o relato sobre a infraestrutura. A equipe de operações já está analisando e manteremos você atualizado.', 0.91, 'seed', 'triagem-v1', 'REJEITADA', NULL, 1, 1624, 381, 173, 'Ana Atendente', pg_temp.ha(30665), pg_temp.ha(30684), pg_temp.ha(30684)),
  (12, 2, 'ALTA', 'Cobrança em duplicidade no cartão. Fui cobrado duas vezes pela mesma assinatura neste mês. Preciso do estorno de uma das cobranças.', 'Olá! Recebemos sua solicitação financeira. Nossa equipe vai conferir os lançamentos e retornar com a correção ou o esclarecimento.', 0.83, 'seed', 'triagem-v1', 'ACEITA', NULL, 1, 820, 437, 127, 'Ana Atendente', pg_temp.ha(34473), pg_temp.ha(34480), pg_temp.ha(34480)),
  (13, 2, 'MEDIA', 'Relatório de pagamentos com totais divergentes. O total exibido no relatório de pagamentos não bate com a soma das linhas exportadas para planilha.', 'Olá! Recebemos sua solicitação financeira. Nossa equipe vai conferir os lançamentos e retornar com a correção ou o esclarecimento.', 0.77, 'seed', 'triagem-v1', 'ACEITA', NULL, 1, 2181, 612, 257, 'Ana Atendente', pg_temp.ha(40784), pg_temp.ha(40819), pg_temp.ha(40819)),
  (14, 2, 'BAIXA', 'Atualizar dados de faturamento. Precisamos atualizar a razão social e o endereço que aparecem nas notas fiscais emitidas.', 'Olá! Recebemos sua solicitação financeira. Nossa equipe vai conferir os lançamentos e retornar com a correção ou o esclarecimento.', 0.81, 'seed', 'triagem-v1', 'ACEITA', NULL, 1, 1425, 536, 215, 'Ana Atendente', pg_temp.ha(57639), pg_temp.ha(57673), pg_temp.ha(57673)),
  (15, 2, 'MEDIA', 'Pagamento confirmado mas fatura segue em aberto. Paguei o boleto na segunda-feira e a fatura continua aparecendo como em aberto no portal.', 'Olá! Recebemos sua solicitação financeira. Nossa equipe vai conferir os lançamentos e retornar com a correção ou o esclarecimento.', 0.87, 'seed', 'triagem-v1', 'ACEITA', NULL, 1, 923, 447, 159, 'Ana Atendente', pg_temp.ha(5394), pg_temp.ha(5411), pg_temp.ha(5411)),
  (16, 2, 'CRITICA', 'Integração bancária parou de importar extratos. A conciliação automática não importa extratos desde ontem. O fechamento do mês depende disso.', 'Olá! Recebemos sua solicitação financeira. Nossa equipe vai conferir os lançamentos e retornar com a correção ou o esclarecimento.', 0.73, 'seed', 'triagem-v1', 'ACEITA', NULL, 1, 2464, 601, 135, 'Ana Atendente', pg_temp.ha(28361), pg_temp.ha(28369), pg_temp.ha(28369)),
  (17, 3, 'ALTA', 'Erro 500 ao salvar cadastro de cliente. Ao clicar em salvar no cadastro de clientes aparece erro 500. Acontece com qualquer cliente novo.', 'Olá! Obrigado por relatar o problema. Já encaminhamos para o time técnico reproduzir o erro e retornaremos com uma previsão de correção.', 0.62, 'seed', 'triagem-v1', 'CONCLUIDA', NULL, 1, 1694, 566, 164, NULL, NULL, pg_temp.ha(2406), pg_temp.ha(2406)),
  (18, 3, 'MEDIA', 'Filtro por data não traz resultados. Na tela de pedidos, ao filtrar por período, a lista fica vazia mesmo havendo pedidos nas datas informadas.', 'Olá! Obrigado por relatar o problema. Já encaminhamos para o time técnico reproduzir o erro e retornaremos com uma previsão de correção.', 0.94, 'seed', 'triagem-v1', 'ACEITA', NULL, 1, 1243, 552, 183, 'Ana Atendente', pg_temp.ha(56852), pg_temp.ha(56884), pg_temp.ha(56884)),
  (19, 5, 'CRITICA', 'Texto cortado no botão de exportar. No celular o texto do botão exportar fica cortado e não dá para ler a opção.', 'Olá! Recebemos o relato sobre a infraestrutura. A equipe de operações já está analisando e manteremos você atualizado.', 0.67, 'seed', 'triagem-v1', 'REJEITADA', NULL, 1, 819, 616, 248, 'Ana Atendente', pg_temp.ha(37853), pg_temp.ha(37861), pg_temp.ha(37861)),
  (20, 3, 'CRITICA', 'Pedidos duplicados ao confirmar compra. Clientes relatam que ao confirmar a compra o pedido é criado duas vezes e o estoque baixa em dobro.', 'Olá! Obrigado por relatar o problema. Já encaminhamos para o time técnico reproduzir o erro e retornaremos com uma previsão de correção.', 0.57, 'seed', 'triagem-v1', 'ACEITA', NULL, 1, 1740, 361, 157, 'Ana Atendente', pg_temp.ha(80879), pg_temp.ha(80888), pg_temp.ha(80888)),
  (21, 3, 'MEDIA', 'Upload de anexo falha com arquivos PDF. Ao anexar arquivos PDF acima de 2 MB o upload fica em 99% e depois mostra erro genérico.', 'Olá! Obrigado por relatar o problema. Já encaminhamos para o time técnico reproduzir o erro e retornaremos com uma previsão de correção.', 0.78, 'seed', 'triagem-v1', 'ACEITA', NULL, 1, 781, 361, 217, 'Ana Atendente', pg_temp.ha(57195), pg_temp.ha(57242), pg_temp.ha(57242)),
  (22, 3, 'ALTA', 'Relatório de vendas trava o navegador. Ao gerar o relatório de vendas do trimestre o navegador congela e precisa ser fechado.', 'Olá! Obrigado por relatar o problema. Já encaminhamos para o time técnico reproduzir o erro e retornaremos com uma previsão de correção.', 0.66, 'seed', 'triagem-v1', 'ACEITA', NULL, 1, 968, 473, 227, 'Ana Atendente', pg_temp.ha(38473), pg_temp.ha(38498), pg_temp.ha(38498)),
  (23, 3, 'BAIXA', 'Ordenação da tabela de produtos invertida. Ao ordenar produtos por nome a lista vem de Z para A mesmo selecionando a ordem crescente.', 'Olá! Obrigado por relatar o problema. Já encaminhamos para o time técnico reproduzir o erro e retornaremos com uma previsão de correção.', 0.58, 'seed', 'triagem-v1', 'CONCLUIDA', NULL, 1, 1136, 579, 177, NULL, NULL, pg_temp.ha(2049), pg_temp.ha(2049)),
  (24, 3, 'MEDIA', 'Notificações duplicadas no painel. Cada aviso aparece duas vezes no sino de notificações do painel principal.', 'Olá! Obrigado por relatar o problema. Já encaminhamos para o time técnico reproduzir o erro e retornaremos com uma previsão de correção.', 0.66, 'seed', 'triagem-v1', 'ACEITA', NULL, 1, 1597, 598, 187, 'Ana Atendente', pg_temp.ha(21636), pg_temp.ha(21680), pg_temp.ha(21680)),
  (25, 4, 'BAIXA', 'Como exportar a lista de clientes. Gostaria de saber se é possível exportar a lista de clientes em CSV e onde fica essa opção.', 'Olá! Obrigado pela pergunta. Vamos reunir as informações e responder com o passo a passo em seguida.', 0.92, 'seed', 'triagem-v1', 'ACEITA', NULL, 1, 912, 388, 177, 'Ana Atendente', pg_temp.ha(5332), pg_temp.ha(5344), pg_temp.ha(5344)),
  (26, 4, 'BAIXA', 'Diferença entre perfis de usuário. Qual a diferença entre o perfil gestor e o perfil analista? Preciso definir o perfil de um novo colaborador.', 'Olá! Obrigado pela pergunta. Vamos reunir as informações e responder com o passo a passo em seguida.', 0.84, 'seed', 'triagem-v1', 'ACEITA', NULL, 1, 1116, 455, 239, 'Ana Atendente', pg_temp.ha(24657), pg_temp.ha(24693), pg_temp.ha(24693)),
  (27, 2, 'BAIXA', 'Como configurar aprovação em duas etapas. Queremos que pedidos acima de determinado valor passem por duas aprovações. Isso é configurável?', 'Olá! Recebemos sua solicitação financeira. Nossa equipe vai conferir os lançamentos e retornar com a correção ou o esclarecimento.', 0.55, 'seed', 'triagem-v1', 'REJEITADA', NULL, 1, 2279, 386, 177, 'Ana Atendente', pg_temp.ha(4753), pg_temp.ha(4768), pg_temp.ha(4768)),
  (28, 4, 'BAIXA', 'Onde vejo o histórico de alterações. Existe algum lugar onde consigo ver quem alterou o cadastro de um fornecedor?', 'Olá! Obrigado pela pergunta. Vamos reunir as informações e responder com o passo a passo em seguida.', 0.59, 'seed', 'triagem-v1', 'ACEITA', NULL, 1, 2508, 396, 249, 'Ana Atendente', pg_temp.ha(62224), pg_temp.ha(62231), pg_temp.ha(62231)),
  (29, 4, 'BAIXA', 'Limite de usuários do plano. Quantos usuários simultâneos o nosso plano atual permite?', 'Olá! Obrigado pela pergunta. Vamos reunir as informações e responder com o passo a passo em seguida.', 0.7, 'seed', 'triagem-v1', 'CONCLUIDA', NULL, 1, 2330, 340, 201, NULL, NULL, pg_temp.ha(7070), pg_temp.ha(7070)),
  (30, 4, 'MEDIA', 'Integração com planilhas. É possível integrar os relatórios do sistema com planilhas online para atualização automática?', 'Olá! Obrigado pela pergunta. Vamos reunir as informações e responder com o passo a passo em seguida.', 0.69, 'seed', 'triagem-v1', 'CONCLUIDA', NULL, 1, 1846, 528, 149, NULL, NULL, pg_temp.ha(3470), pg_temp.ha(3470)),
  (31, 4, 'BAIXA', 'Treinamento para novos colaboradores. Vocês oferecem material de treinamento para novos usuários do sistema? Temos três pessoas começando.', 'Olá! Obrigado pela pergunta. Vamos reunir as informações e responder com o passo a passo em seguida.', 0.9, 'seed', 'triagem-v1', 'CONCLUIDA', NULL, 1, 750, 411, 195, NULL, NULL, pg_temp.ha(16953), pg_temp.ha(16953)),
  (32, 4, 'BAIXA', 'Personalizar campos do cadastro. Consigo adicionar um campo personalizado no cadastro de produtos para o código interno?', 'Olá! Obrigado pela pergunta. Vamos reunir as informações e responder com o passo a passo em seguida.', 0.61, 'seed', 'triagem-v1', 'ACEITA', NULL, 1, 2136, 375, 207, 'Ana Atendente', pg_temp.ha(58223), pg_temp.ha(58283), pg_temp.ha(58283)),
  (33, 5, 'CRITICA', 'Servidor de arquivos fora do ar. O servidor de arquivos compartilhados não responde desde as 7h. Nenhum setor consegue abrir documentos.', 'Olá! Recebemos o relato sobre a infraestrutura. A equipe de operações já está analisando e manteremos você atualizado.', 0.73, 'seed', 'triagem-v1', 'CONCLUIDA', NULL, 1, 1325, 436, 167, NULL, NULL, pg_temp.ha(3673), pg_temp.ha(3673)),
  (34, 5, 'ALTA', 'VPN desconectando com frequência. A VPN cai a cada 10 minutos para quem trabalha remoto, interrompendo chamadas e acesso aos sistemas.', 'Olá! Recebemos o relato sobre a infraestrutura. A equipe de operações já está analisando e manteremos você atualizado.', 0.66, 'seed', 'triagem-v1', 'CONCLUIDA', NULL, 1, 842, 462, 199, NULL, NULL, pg_temp.ha(416), pg_temp.ha(416)),
  (35, 5, 'MEDIA', 'Impressora do segundo andar não imprime. A impressora do segundo andar recebe os trabalhos mas não imprime. O painel não mostra erro.', 'Olá! Recebemos o relato sobre a infraestrutura. A equipe de operações já está analisando e manteremos você atualizado.', 0.93, 'seed', 'triagem-v1', 'ACEITA', NULL, 1, 936, 453, 155, 'Ana Atendente', pg_temp.ha(34781), pg_temp.ha(34823), pg_temp.ha(34823)),
  (36, 5, 'ALTA', 'Lentidão geral na rede da filial. A filial está com lentidão para acessar qualquer sistema desde a manhã. Testes de velocidade mostram queda grande.', 'Olá! Recebemos o relato sobre a infraestrutura. A equipe de operações já está analisando e manteremos você atualizado.', 0.72, 'seed', 'triagem-v1', 'ACEITA', NULL, 1, 1747, 379, 208, 'Ana Atendente', pg_temp.ha(24052), pg_temp.ha(24093), pg_temp.ha(24093)),
  (37, 5, 'BAIXA', 'Solicitação de monitor adicional. Gostaria de solicitar um segundo monitor para a estação de trabalho do time de análise.', 'Olá! Recebemos o relato sobre a infraestrutura. A equipe de operações já está analisando e manteremos você atualizado.', 0.7, 'seed', 'triagem-v1', 'ACEITA', NULL, 1, 843, 489, 190, 'Ana Atendente', pg_temp.ha(1502), pg_temp.ha(1549), pg_temp.ha(1549)),
  (38, 3, 'ALTA', 'Certificado SSL do portal perto de expirar. O navegador mostra aviso de que o certificado do portal interno expira em cinco dias.', 'Olá! Obrigado por relatar o problema. Já encaminhamos para o time técnico reproduzir o erro e retornaremos com uma previsão de correção.', 0.83, 'seed', 'triagem-v1', 'REJEITADA', NULL, 1, 1835, 385, 159, 'Ana Atendente', pg_temp.ha(43651), pg_temp.ha(43682), pg_temp.ha(43682)),
  (39, 5, 'ALTA', 'Backup noturno falhou. O relatório do backup indica falha na rotina noturna das duas últimas noites.', 'Olá! Recebemos o relato sobre a infraestrutura. A equipe de operações já está analisando e manteremos você atualizado.', 0.67, 'seed', 'triagem-v1', 'CONCLUIDA', NULL, 1, 1822, 320, 187, NULL, NULL, pg_temp.ha(11126), pg_temp.ha(11126)),
  (40, 5, 'MEDIA', 'Wi-Fi da sala de reuniões instável. A rede sem fio da sala de reuniões principal cai durante videochamadas.', 'Olá! Recebemos o relato sobre a infraestrutura. A equipe de operações já está analisando e manteremos você atualizado.', 0.78, 'seed', 'triagem-v1', 'CONCLUIDA', NULL, 1, 2040, 484, 229, NULL, NULL, pg_temp.ha(4729), pg_temp.ha(4729));

-- Ajusta as sequences porque os IDs foram informados explicitamente.
SELECT setval(pg_get_serial_sequence('"usuarios"', 'id'), (SELECT MAX("id") FROM "usuarios"));
SELECT setval(pg_get_serial_sequence('"categorias"', 'id'), (SELECT MAX("id") FROM "categorias"));
SELECT setval(pg_get_serial_sequence('"chamados"', 'id'), (SELECT MAX("id") FROM "chamados"));
